POST http://localhost:8080/add
Content-Type: application/json

{
  "id": 18,
  "isbn": "155776FG",
  "name": "Главные на море",
  "author":"Шустрый Пряник",
  "pageNumber":578,
  "weight":3,
  "price": 457.8
  }
###
POST http://localhost:8080/add
Content-Type: application/json

{
  "id": 9,
  "isbn": "155776FG",
  "name": "Муха в стакане",
  "author":"АУАПЫВВ",
  "pageNumber":666,
  "weight":4,
  "price": 957.8
}
###
POST http://localhost:8080/add
Content-Type: application/json

{
  "id": 22,
  "isbn": "OL23919A",
  "name": "Повесить овечку",
  "author":"OL23919A",
  "pageNumber":578,
  "weight":3,
  "price": 457.8
}
###
POST http://localhost:8080/add
Content-Type: application/json

{
  "id": 179,
  "isbn": "574848-5",
  "name": "Крякатун",
  "author":"OL23919A",
  "pageNumber":778,
  "weight":3,
  "price": 457.8
}
###
GET http://localhost:8080/get/7
Content-Type: application/json

###
GET http://localhost:8080/get
Content-Type: application/json
###

GET http://localhost:8080/find_openlibrary/OL23919A
Content-Type: application/json
###

GET http://localhost:8080/find/7
Content-Type: application/json

###
POST http://localhost:8080/edit
Content-Type: application/json

{
  "id": 10,
  "isbn": "9999-9",
  "name": "Война и Мир",
  "author": "Толстой",
  "pageNumber": 5778,
  "weight":7,
  "price": 9988.80
}
###
POST http://localhost:8080/delete/10
Content-Type: application/json

###
